import argparse
import time
import logging
from core.communication import OmniBus
from core.memory import MemoryGrid
from core.agents import ArchitectAgent, CoderAgent, ReviewerAgent
from core.plugin_manager import PluginManager

# Configure Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [MAIN] - %(levelname)s - %(message)s')
logger = logging.getLogger("MetaEngine")

def main():
    parser = argparse.ArgumentParser(description="Meta-Engineering: Autonomous System")
    parser.add_argument("--start-autonomous-mode", action="store_true", help="Start the autonomous agent swarm")
    parser.add_argument("--load-plugins", action="store_true", help="Load external plugins")
    parser.add_argument("--verbose", action="store_true", help="Enable verbose logging")
    
    args = parser.parse_args()

    print("\nMeta-Engineering System v1.0")
    print("=================================")

    if args.start_autonomous_mode:
        run_autonomous_mode()
    else:
        print("System ready. Use --start-autonomous-mode to ignite the swarm.")

def run_autonomous_mode():
    logger.info("Initializing Core Systems...")
    
    # 1. Initialize Nervous System
    bus = OmniBus()

    # 1.5 Load Plugins
    pm = PluginManager()
    pm.discover_plugins()
    
    # 2. Initialize Memory Grid
    memory = MemoryGrid()
    
    # 3. Wake up Agents
    architect = ArchitectAgent("DaVinci")
    coder = CoderAgent("Lovelace")
    reviewer = ReviewerAgent("Torvalds")
    
    agents = [architect, coder, reviewer]
    logger.info(f"Agents Online: {[a.name for a in agents]}")

    # 4. Subscribe Agents to Channels
    # In a real system, agents would subscribe themselves based on their roles.
    # Here we simulate the message flow.
    
    def on_plan_created(message):
        logger.info(f"EVENT: Plan received from {message['sender']}")
        tasks = message.get("content", [])
        for task in tasks:
            # Dispatch to Coder
            bus.publish("coding_tasks", {"sender": "system", "task": task})

    def on_code_generated(message):
        logger.info(f"EVENT: Code generated by {message['sender']}")
        code = message.get("content")
        # Dispatch to Reviewer
        bus.publish("code_review", {"sender": "system", "code": code})

    def on_review_completed(message):
        logger.info(f"EVENT: Review result from {message['sender']}: {message['content']}")

    # Wiring the callbacks manually for simulation
    bus.subscribe("plans", on_plan_created)
    bus.subscribe("coding_tasks", lambda msg: perform_agent_task(coder, msg))
    bus.subscribe("code_review", lambda msg: perform_agent_task(reviewer, msg))
    bus.subscribe("reviews", on_review_completed)

    logger.info("--- SWARM ACTIVATED ---")
    
    # Trigger the chain
    initial_intent = "Build a login system"
    logger.info(f"Injecting Intent: {initial_intent}")
    
    # Architect starts thinking
    result = architect.think({"intent": initial_intent})
    if result.status == "success":
        action_res = architect.act(result.payload)
        # Publish the plan
        bus.publish("plans", {
            "sender": architect.name,
            "content": result.payload
        })

    # Keep alive for async processing (simulated)
    time.sleep(2)
    logger.info("--- SIMULATION COMPLETE ---")

def perform_agent_task(agent, message):
    """Helper to bridge pub/sub message to agent logic"""
    if agent.role == "Coder" and "task" in message:
        res = agent.think({"task": message["task"]})
        if res.status == "success":
            act_res = agent.act(res.payload)
            # Publish the result including the file_path if available
            bus = OmniBus()
            bus.publish("code_review", {
                "sender": agent.name, 
                "content": act_res.payload,
                "file_path": act_res.metadata.get("file_path") if act_res.metadata else None
            })
        
    elif agent.role == "Reviewer":
        file_path = message.get("file_path")
        code_to_review = message.get("code") or message.get("content")
        
        res = agent.think({"code": code_to_review, "file_path": file_path})
        act_res = agent.act(res.payload)
        OmniBus().publish("reviews", {"sender": agent.name, "content": act_res.payload})

if __name__ == "__main__":
    main()
